version: "3"

services:
    be-compose:
        image: fuderrpham/be_cyber_media:latest
        container_name: be-source-api-compose
        ports:
            - "3070:3069"
        depends_on:
            - mysql-compose
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - JWT_SECRET_KEY=${JWT_SECRET_KEY}
            - ACCESS_TOKEN_SECRET = ${ACCESS_TOKEN_SECRET}
            - ACCESS_TOKEN_EXPIRE = ${ACCESS_TOKEN_EXPIRE}
            - REFRESH_TOKEN_SECRET = ${REFRESH_TOKEN_SECRET}
            - REFRESH_TOKEN_EXPIRE = ${REFRESH_TOKEN_EXPIRE}
            - CLOUDIARY_SECRET = ${CLOUDIARY_SECRET}
        command: ["npm", "run", "start"]

    mysql-compose:
        image: mysql
        container_name: some-mysql-compose
        environment:
            - MYSQL_ROOT_PASSWORD=123
        ports:
            - "3305:3306"
