name: CD Docker

#when need to start
on:
    workflow_run:
        workflows: ["CI_Docker"]
        types:
            - completed

#what is the jobs
jobs:
    build:
        runs-on: node_45

        steps:
            - name: Xóa file .env cũ
              run: sudo rm -f .env

            - name: Tạo file .env mới
              run: |
                  echo "DATABASE_URL=mysql://root:123@some-mysql-compose:3306/db_media" >> .env
                  echo "JWT_SECRET_KEY=demotokenforauthentication" >> .env
                  echo "ACCESS_TOKEN_SECRET=KHOABIMAT_ACCESSTOKEN" >> .env
                  echo "ACCESS_TOKEN_EXPIRE=2m" >> .env
                  echo "REFRESH_TOKEN_SECRET=KHOABIMAT_REFRESHTOKEN" >> .env
                  echo "REFRESH_TOKEN_EXPIRE=7d" >> .env
                  echo "CLOUDIARY_SECRET=Y4bTq2JKnHagV-lg3-PU5mVt_mc" >> .env

            - name: Dừng và xóa container BE
              run: |
                  sudo docker container stop be-source-api-compose || true
                  sudo docker container remove be-source-api-compose || true
            - name: XÓa image cũ
              run: sudo docker image remove fuderrpham/be_cyber_media:latest || true

            - name: chạy lại với docker compose
              run: docker compose up -d
